### PR TITLE
creating new issues expects PUT request

### PR DESCRIPTION
**Pull request by REDLINK**
Creating a new issues with

$youTrack->createIssue()

results in:

Error for 'https://server/rest/issue?type=Bug&project=ST&summary=Test2015-05-1316%3A13%3A44': 413

Tested using YouTrack 6.0

The use of PUT is described here:
https://confluence.jetbrains.com/display/YTD6/Create+New+Issue

### CODE REVIEW

**Comment by REDLINK** [comment]
Using POST and sending all parameters in the body and no parameters in the query string also works.

**Comment by nepda** [comment]
`PUT` will not return the created issue. This might be a problem for some applications using this library (like mine). I will change the method back to `POST`, and move all parameters into the body.

Please check, if the error comes up again.

**Comment by REDLINK** [comment]
Works for us too.

We recently run into the same problem (no returned issue).
The only point with using POST is, that we found nothing about it in the YouTrack documentation https://confluence.jetbrains.com/display/YTD6/Create+New+Issue

So we implemented the correct use of PUT followed by a call to getIssue() to get the created issue information. You can have a look at the implemtation
https://github.com/REDLINK/youtrack/commits/fix-createIssue

By the way, there will be a YouTrack-API redesign http://blog.jetbrains.com/youtrack/2015/04/youtrack-6-5-roadmap/, maybe there will be some changes to PUT/POST.

**Comment by nepda** [comment]
Okay, thank you for the redesign link. I will wathc the progress of the new API design.

**Pull request merged**
